title: "Chamada Hacktoberfest 2020"
email: abel.s.siqueira@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chamada para o Hacktoberfest 2020.
baseurl: "/hacktoberfest2020-chamada" # the subpath of your site, e.g. /blog
url: "https://cidamo.com.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: abel_siqueira
github_username:  abelsiqueira

# Build settings
# theme: jekyll-theme-architect

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .history
#   - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
